# Uncomment the next line to define a global platform for your project
# platform :iOS, '10.0'

target 'TriumphSwiftTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase'
  pod 'FirebaseDatabase'
  pod 'SDWebImage'
  pod 'SwiftSpinner'

end
